-- DB링크 생성하기
CREATE DATABASE LINK KOPOSERVER
CONNECT TO kopo
IDENTIFIED BY kopo
Using 'SGDB';

-- DB링크 조회하기
select * from ALL_DB_LINKS;

-- DB링크를 이용해서 자신의 서버에 DB링크의 데이터를 저장하기
CREATE TABLE PRO_PROMOTION
AS
select *
from PRO_PROMOTION@KOPOSERVER;

select * from CUSTOMERDATA;

SELECT DISTINCT EMI FROM CUSTOMERDATA;

SELECT A.EMI AS WHAT,
    SYSDATE AS NOW
FROM CUSTOMERDATA A;

SELECT *
FROM TABS;