SELECT A.ITEM,
    A.TARGETWEEK,
    A.PLANWEEK,
    A.MAP_PRICE,
    A.PRO_PERCENT,
    MAP_PRICE*PRO_PERCENT AS PROMOTION_EF
FROM PRO_PROMOTION A;

SELECT A.*
FROM PRO_PROMOTION A;

SELECT 'PREDICT_MODEL' AS MEASUREID, 
    A.*,--A테이블의 모든컬럼
    SYSDATE AS TIMEFLAG
FROM CUSTOMERDATA A;

SELECT SYSDATE AS NOW, 
    'KOPO_D510' AS MEASUREID,
    B.*
FROM KOPO_PRODUCT_VOLUME B;

SELECT A.*,
    A.CUSTID||'_'||A.CUSTTYPE AS NEWCOLE2,
    CONCAT(A.CUSTID,CONCAT('_',A.CUSTTYPE)) AS NEWCOL,
    1234 AS BANKID,
    'HK_BANK' AS BANKNAME
FROM CUSTOMERDATA A;

SELECT NAME
    DATA
FROM KOPO_HK1-- UNION과 UNION ALL을 외울 필요 없이 그때마다 검색해서 쓰자!!
UNION
SELECT NAME
    DATA
FROM KOPO_HK2;

SELECT *
FROM KOPO_CHANNEL_RESULT;


SELECT *
FROM CUSTOMERDATA
WHERE AVGPRICE >=3000
AND CUSTTYPE = 'Sleeping-dog';

SELECT EMI, CUSTTYPE
FROM CUSTOMERDATA;

SELECT *
FROM KOPO_CHANNEL_RESULT
WHERE PRODUCTGROUP = 'MOBILE'
UNION all
SELECT *
FROM KOPO_CHANNEL_RESULT
WHERE PRODUCTGROUP = 'WM';

SELECT DISTINCT ACCOUNTNAME, ACCOUNTID
FROM KOPO_CHANNEL_RESULT
WHERE AP2ID = 'A01';

SELECT DISTINCT A.PRODUCTGROUP AS PRODUCT, 
SYSDATE AS NOW
FROM KOPO_PRODUCT_VOLUME A;