SELECT REGIONID,        -- 지역아이디
    PRODUCTGROUP,       -- 상품군
    YEARWEEK            -- 연주차정보
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1               -- WHERE조건을 깔끔하게 넘겨주기 위한것
AND YEARWEEK > 201514   -- OR을 사용해도 되지만 쿼리를 작성할때 OR를 잘 안슴
AND YEARWEEK < 201517
AND PRODUCTGROUP = 'ST0002';

SELECT 'SMART'||'_'||'TECH' AS EXPR
FROM DUAL;

SELECT CONCAT('11', '22') AS EXPR
FROM DUAL;

SELECT POWER(5,3) AS POW
FROM DUAL;

SELECT A.*,
    CEIL(2.354334213) AS TEST_TABLE -- 올림
FROM KOPO_PRODUCT_VOLUME A;

SELECT A.*,
    ROUND((YEARWEEK * 0.1245871262), 6) AS TEST -- 반올림
FROM KOPO_PRODUCT_VOLUME A;

SELECT A.*,
    FLOOR((YEARWEEK * 0.124)) AS TEST_TABLE -- 버림
FROM KOPO_PRODUCT_VOLUME A;

SELECT A.*,
    ROUND((PMAP * 0.9)) AS PMAP10
FROM KOPO_PROMOTION A;

SELECT A.*,
    ROUND((PMAP/MAP_PRICE)*100, 0)||'%' AS PERCENT
FROM KOPO_PROMOTION A;

SELECT A.*,
    FLOOR(PLANWEEK/TARGETWEEK) AS TSET
FROM KOPO_PROMOTION A;

SELECT *
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND YEARWEEK BETWEEN 201501 AND 201503;

SELECT DISTINCT ACCOUNTNAME
FROM (
    SELECT *
    FROM KOPO_CHANNEL_RESULT
    WHERE 1=1
    AND ACCOUNTNAME
    IN (SELECT ACCOUNTNAME
        FROM ACCOUNT_NOT_IN)
);

SELECT ACCOUNTNAME
FROM ACCOUNT_NOT_IN;

SELECT DISTINCT ACCOUNTNAME
FROM KOPO_CHANNEL_RESULT;

SELECT *
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND ACCOUNTNAME IN ('BNH', 'DNH')
AND PRODUCTGROUP IN ('TV');

SELECT *
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND ACCOUNTNAME LIKE '%CHANNEL%';

-- NULL=빈값을 의미함

SELECT *
FROM NULL_CHECK
WHERE 1=1
AND B IS NULL;
SELECT DISTINCT ACCOUNTNAME
FROM KOPO_CHANNEL_RESULT;

SELECT *
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND ACCOUNTNAME IN ('NEXCOM', 'BNH');

SELECT *
FROM NULL_CHECK2;

SELECT *
FROM NULL_CHECK2
WHERE 1=1
AND TRIM(NAMEC,' ', '')='';

SELECT *
FROM KOPO_PRODUCT_VOLUME;

SELECT REGIONID,
    'ST0001' AS PRODUCTGROUP,
    YEARWEEK,
    VOLUME
FROM KOPO_PRODUCT_VOLUME
UNION
SELECT *
FROM KOPO_PRODUCT_VOLUME;

INSERT INTO KOPO_PRODUCT_VOLUME
SELECT REGIONID, 
'ST0003' AS PRODUCTGROUP,
YEARWEEK,
VOLUME
FROM KOPO_PRODUCT_VOLUME;

SELECT *
FROM KOPO_PRODUCT_VOLUME2
WHERE 1=1
AND PRODUCTGROUP IN ('ST0001')
AND YEARWEEK IN(SELECT YEARWEEK2
                FROM HOLIDAY_TABLE
                WHERE 1=1
                AND HOLIDAY_NAME IN('BF'));

SELECT YEARWEEK2
FROM HOLIDAY_TABLE
WHERE 1=1
AND HOLIDAY_NAME IN('BF');

SELECT *
FROM TABS;

SELECT *
FROM TABS
WHERE 1=1
AND AVG_ROW_LEN>20;

SELECT DISTINCT product
FROM TEST111;

SELECT *
FROM TEST111;