SELECT REGIONID,        -- 지역아이디
    PRODUCTGROUP,       -- 상품군
    YEARWEEK            -- 연주차정보
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1               -- WHERE조건을 깔끔하게 넘겨주기 위한것
AND YEARWEEK > 201514   -- OR을 사용해도 되지만 쿼리를 작성할때 OR를 잘 안슴
AND YEARWEEK < 201517
AND PRODUCTGROUP = 'ST0002';

SELECT 'SMART'||'_'||'TECH' AS EXPR
FROM DUAL;

SELECT CONCAT('11', '22') AS EXPR
FROM DUAL;

SELECT POWER(5,3) AS POW
FROM DUAL;

SELECT A.*,
    CEIL(2.354334213) AS TEST_TABLE -- 올림
FROM KOPO_PRODUCT_VOLUME A;

SELECT A.*,
    ROUND((YEARWEEK * 0.1245871262), 6) AS TEST -- 반올림
FROM KOPO_PRODUCT_VOLUME A;

SELECT A.*,
    FLOOR((YEARWEEK * 0.124)) AS TEST_TABLE -- 버림
FROM KOPO_PRODUCT_VOLUME A;

SELECT A.*,
    ROUND((PMAP * 0.9)) AS PMAP10
FROM KOPO_PROMOTION A;

SELECT A.*,
    ROUND((PMAP/MAP_PRICE)*100, 0)||'%' AS PERCENT
FROM KOPO_PROMOTION A;

SELECT A.*,
    FLOOR(PLANWEEK/TARGETWEEK) AS TSET
FROM KOPO_PROMOTION A;

SELECT *
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND YEARWEEK BETWEEN 201501 AND 201503;

SELECT DISTINCT ACCOUNTNAME
FROM (
    SELECT *
    FROM KOPO_CHANNEL_RESULT
    WHERE 1=1
    AND ACCOUNTNAME
    IN (SELECT ACCOUNTNAME
        FROM ACCOUNT_NOT_IN)
);

SELECT *
FROM ACCOUNT_NOT_IN;

SELECT DISTINCT ACCOUNTNAME
FROM KOPO_CHANNEL_RESULT;

SELECT *
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND ACCOUNTNAME IN ('BNH', 'DNH')
AND PRODUCTGROUP IN ('TV');

SELECT *
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND ACCOUNTNAME LIKE '%CHANNEL%';

-- NULL=빈값을 의미함

SELECT *
FROM NULL_CHECK
WHERE 1=1
AND B IS NULL;
SELECT DISTINCT ACCOUNTNAME
FROM KOPO_CHANNEL_RESULT;

SELECT *
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND ACCOUNTNAME IN ('NEXCOM', 'BNH');

SELECT *
FROM NULL_CHECK2;

SELECT *
FROM NULL_CHECK2
WHERE 1=1
AND TRIM(NAMEC,' ', '')='';

SELECT *
FROM KOPO_PRODUCT_VOLUME;

SELECT REGIONID,
    'ST0001' AS PRODUCTGROUP,
    YEARWEEK,
    VOLUME
FROM KOPO_PRODUCT_VOLUME
UNION
SELECT *
FROM KOPO_PRODUCT_VOLUME;

INSERT INTO KOPO_PRODUCT_VOLUME
SELECT REGIONID, 
'ST0003' AS PRODUCTGROUP,
YEARWEEK,
VOLUME
FROM KOPO_PRODUCT_VOLUME;

SELECT *
FROM KOPO_PRODUCT_VOLUME2
WHERE 1=1
AND PRODUCTGROUP IN ('ST0001')
AND YEARWEEK IN(SELECT YEARWEEK2
                FROM HOLIDAY_TABLE
                WHERE 1=1
                AND HOLIDAY_NAME IN('BF'));

SELECT YEARWEEK2 --홀리데이 테이블에서 홀리데이 네임컬럼이 BF인 것만 선정해 YEARWEEK컬럼만 보여줌
FROM HOLIDAY_TABLE
WHERE 1=1
AND HOLIDAY_NAME IN('BF');

SELECT *
FROM TABS;

SELECT *
FROM TABS
WHERE 1=1
AND AVG_ROW_LEN>20;

SELECT DISTINCT regionname
FROM TEST111;

SELECT *
FROM TEST111;

SELECT A.*
FROM TEST111 A;

SELECT AP1NAME
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND AP1NAME_NAME IN ('WEST');

SELECT DISTINCT ACCOUNTNAME
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND AP1NAME IN ('WEST')
AND YEARWEEK >201720;

select *
from KOPO_CHANNEL_RESULT;

SELECT DISTINCT ACCOUNTNAME
FROM KOPO_CHANNEL_RESULT;

SELECT DISTINCT ACCOUNTNAME
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND AP1NAME IN ('WEST')
AND YEARWEEK > 201720;

SELECT *
FROM KOPO_PRODUCT_VOLUME_QUIZ
WHERE 1=1
AND REGIONID IN ('A01');

SELECT 'A02' AS REGIONID,
    PRODUCTGROUP,
    YEARWEEK,
    VOLUME
FROM KOPO_PRODUCT_VOLUME_QUIZ
UNION
SELECT *
FROM KOPO_PRODUCT_VOLUME_QUIZ;

SELECT *
FROM KOPO_PRODUCT_VOLUME_QUIZ;

SELECT DISTINCT AP2ID
FROM KOPO_CHANNEL_RESULT;

SELECT DISTINCT ACCOUNTNAME
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND AP1NAME = 'WEST'
AND YEARWEEK >= 201720;

SELECT DISTINCT YEARWEEK
FROM(
    SELECT *
    FROM KOPO_CHANNEL_RESULT
    WHERE 1=1
    AND YEARWEEK IN ('201720','201721')
);

SELECT DISTINCT YEARWEEK
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND YEARWEEK IN ('201720','201721');

SELECT *
FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND PRODUCTGROUP = &intv
AND YEARWEEK = &inyearweek;

SELECT *
FROM KOPO_CHANNEL_RESULT
ORDER BY YEARWEEK;-- 정렬

SELECT AP2ID, SALESID, ITEM, YEARWEEK, QTY
FROM KOPO_CHANNEL_RESULT
ORDER BY AP2ID, SALESID, ITEM, YEARWEEK, QTY;

SELECT REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
ORDER BY REGIONID ASC, PRODUCTGROUP ASC, YEARWEEK ASC; --오름차순으로 정렬

SELECT REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
ORDER BY REGIONID DESC, PRODUCTGROUP DESC, YEARWEEK DESC; --내림차순으로 정렬

SELECT UPPER(REGIONID) AS REGIONID
FROM KOPO_PRODUCT_VOLUME; -- 컬럼의 제목이 아닌 내용을 대문자로 바꿈

SELECT LOWER(REGIONID) AS REGIONID
FROM KOPO_PRODUCT_VOLUME; -- 컬럼의 제목이 아닌 내용을 소문자로 바꿈

SELECT *
FROM LOGIN_TABLE;

SELECT *
FROM LOGIN_TABLE
WHERE UPPER(ID) = UPPER('mAnaGeR');

SELECT A.*,--합치는놈
        CONCAT(REGIONID, PRODUCTGROUP) AS IDX,
        REGIONID||'_'||PRODUCTGROUP AS IDX2,
        CONCAT(REGIONID, CONCAT(PRODUCTGROUP,YEARWEEK)) AS KEY_VALUE
FROM KOPO_PRODUCT_VOLUME A;


SELECT A.YEARWEEK, 
    SUBSTR(YEARWEEK,0,4) AS YEAR,-- 0=시작점(1과 동일), 4=몇개를 가져올지
    SUBSTR(YEARWEEK,5,2) AS WEEK,-- 5=시작점, 2=몇개를 가져올지
    SUBSTR(YEARWEEK,5,1) AS WEEK2-- 5=시작점, 1=몇개를 가져올지
FROM KOPO_PRODUCT_VOLUME A;

SELECT A.*, --채우는놈
       LPAD(UPPER(CUSTID), 10,'*') AS CSID
FROM CUSTOMERDATA A;

SELECT LPAD(A.CUSTOMERCODE, 12, '*') AS CUSTOMERCODE,
A.*
FROM KOPO_CUSTOMERDATA A;

SELECT A.*,--지우는놈
       LTRIM(A.PRODUCT, 'PRO')
FROM KOPO_CHANNEL_SEASONALITY_NEW A;

--TRIM (공백제거)
--NULL체크전에 TRIM을 갈기고 NULL 체크시작
SELECT LENGTH(TRIM('            AAAA           ')) AS CASE1
FROM DUAL;

--컬럼내의 ~~를 ##으로 바꿔줌
SELECT REPLACE(A.REGIONID, 'A', 'NATION_') AS REGIONID,
       A.*
FROM KOPO_CHANNEL_SEASONALITY_NEW A;

SELECT REPLACE(LPAD(CUSTOMERCODE, 10,'0'), SUBSTR(LPAD(CUSTOMERCODE, 10,'0'), 7, 4), '****') AS CUSTOMERCODE
FROM KOPO_CUSTOMERDATA;

SELECT LPAD(CUSTOMERCODE, 10,'0')
FROM KOPO_CUSTOMERDATA;