CREATE TABLE KOPO_PARAMETER_LEEWONJIN(
    PARAM_NAME VARCHAR2(100),
    PARAM_VALUE VARCHAR2(100)
);

INSERT INTO KOPO_PARAMETER_LEEWONJIN
VALUES ('SRC_TABLE', 'kopo_bankdata');

INSERT INTO KOPO_PARAMETER_LEEWONJIN
VALUES ('SRC_CON', 'mysql+pymysql://kopo:kopo@192.168.110.111:3306/kopo');

INSERT INTO KOPO_PARAMETER_LEEWONJIN
VALUES ('DEST_TABLE', 'kopo_bankdata_leewonjin');

INSERT INTO KOPO_PARAMETER_LEEWONJIN
VALUES ('DEST_CON', 'oracle+cx_oracle://kopo:kopo@192.168.110.112:1521/orcl');

SELECT *
FROM KOPO_PARAMETER_LEEWONJIN;

SELECT *
FROM KOPO_BANKDATA_LEEWONJIN;