SELECT * 
FROM KOPO_CHANNEL_SEASONALITY_NEW
WHERE 1=1
AND REGIONID IN ('A44')
AND PRODUCT IN ('PRODUCT1');

SELECT SUM(QTY) AS SUM_QTY,
       MAX(YEARWEEK) AS MAX_YEARWEEK,
       MIN(YEARWEEK) AS MIN_YEARWEEK,
       COUNT(QTY) AS QTY_COUNT
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT COUNT(*)
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT COUNT(*)
FROM 
( SELECT *
  FROM KOPO_CHANNEL_SEASONALITY_NEW
);

SELECT REGIONID, PRODUCT,
       SUM(QTY) AS SUM_QTY,
       MAX(QTY) AS MAX_QTY,
       MIN(QTY) AS MIN_QTY,
       AVG(QTY) AS AVG_QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW
GROUP BY REGIONID, PRODUCT
ORDER BY SUM(QTY);

SELECT YEAR, SALESNAME,
        SUM(QTY) AS SUM_QTY,
        AVG(QTY) AS AVG_QTY
FROM KOPO_CHANNEL_RESULT
GROUP BY YEAR, SALESNAME 
HAVING SUM(QTY)>5 -- GROUP BY 다음에 오는 조건 (WHERE절처럼 사용 가능)
ORDER BY SUM(QTY), AVG(QTY) DESC;

SELECT YEAR,
       SUM(QTY) AS SUM_QTY,
       AVG(QTY) AS AVG_QTY
FROM KOPO_CHANNEL_RESULT
GROUP BY YEAR
ORDER BY SUM(QTY), AVG(QTY) DESC;


SELECT ACCOUNTNAME, COUNT (QTY) AS ACCOUNT_COUNT
FROM KOPO_CHANNEL_RESULT
WHERE AP2ID IN('A01', 'A02', 'A03' , 'A04')
GROUP BY ACCOUNTNAME;

SELECT *
FROM(  SELECT ACCOUNTNAME,
       'KOPO_'|| ACCOUNTNAME AS NEW_ACCOUNT,
       COUNT (QTY) AS ACCOUNT_COUNT
       FROM KOPO_CHANNEL_RESULT
       WHERE AP2ID IN('A01', 'A02', 'A03', 'A04')
       GROUP BY ACCOUNTNAME)
WHERE 1=1
AND NEW_ACCOUNT LIKE 'KOPO%';

SELECT *
FROM KOPO_CHANNEL_SEASONALITY_NEW
WHERE 1=1
AND REGIONID IN (SELECT DISTINCT REGIONID
                 FROM KOPO_PRODUCT_VOLUME);

SELECT COUNT(DISTINCT REGIONID) AS REGION_NEW
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND REGIONID IN ('A01');

SELECT *
FROM REGION_MST_HK;

SELECT *
FROM KOPO_CHANNEL_SEASONALITY_NEW
WHERE 1=1
AND 'KOPO_'||REGIONID IN (SELECT REGIONID FROM REGION_MST_HK);

SELECT *
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND 'KOPO_'||REGIONID IN (SELECT REGIONID FROM REGION_MST_HK);

SELECT A.*,
     (SELECT AVG(QTY)
     FROM KOPO_CHANNEL_SEASONALITY_NEW
     WHERE REGIONID = A.REGIONID
     AND PRODUCT = A.PRODUCT
     GROUP BY A.REGIONID, A.PRODUCT) AS SUM_QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A;

SELECT A.REGIONID,
       A.PRODUCT,
       A.YEARWEEK,
       A.QTY,
       (SELECT AVG(B.QTY)
        FROM KOPO_CHANNEL_SEASONALITY_NEW B
        WHERE 1=1
        AND B.REGIONID = A.REGIONID 
        AND B.PRODUCT = A.PRODUCT
        ) AS AVG_QTY
from KOPO_CHANNEL_SEASONALITY_NEW A;

SELECT AVG(B.QTY)
FROM KOPO_CHANNEL_SEASONALITY_NEW B
WHERE 1=1
AND B.REGIONID = 'A60'
AND B.PRODUCT = 'PRODUCT4';

SELECT A.*, B.AVG_QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
LEFT JOIN(        
            SELECT REGIONID,
               PRODUCT,
               AVG(QTY) AS AVG_QTY
            FROM KOPO_CHANNEL_SEASONALITY_NEW
            GROUP BY REGIONID, PRODUCT
         )B
ON A.REGIONID = B.REGIONID
AND A.PRODUCT = B.PRODUCT;


WITH A AS
     (SELECT *
     FROM KOPO_CHANNEL_RESULT
     WHERE 1=1
     AND AP2ID IN ('A01','A02'))
SELECT * FROM A;

SELECT *
FROM(SELECT *
     FROM KOPO_CHANNEL_RESULT
     WHERE 1=1
     AND AP2ID IN ('A01','A02'));

SELECT COUNT(*)
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT COUNT(*)
FROM KOPO_REGION_MST;

SELECT (SELECT COUNT(*) FROM KOPO_REGION_MST) * 
       (SELECT COUNT(*) FROM KOPO_CHANNEL_SEASONALITY_NEW) AS CALCUL
FROM DUAL;

SELECT A.REGIONID, 
       B.REGIONNAME,
       A.PRODUCT,
       A.YEARWEEK,
       A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
INNER JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;

SELECT A.REGIONID, 
       B.REGIONNAME,
       A.PRODUCT,
       A.YEARWEEK,
       A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
LEFT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;

SELECT A.REGIONID,
       B.REGIONNAME,
       A.PRODUCT,
       A.YEARWEEK,
       A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
RIGHT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;

SELECT A.REGIONID,
       B.REGIONNAME,
       A.PRODUCT,
       A.YEARWEEK,
       A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
FULL OUTER JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;

SELECT DISTINCT A.REGIONID
FROM KOPO_REGION_MST A
WHERE 1=1
AND A.REGIONID NOT IN (SELECT REGIONID
                       FROM KOPO_CHANNEL_SEASONALITY_NEW);

--SEASONALITY의 REGIONID값 70        
SELECT DISTINCT REGIONID
FROM KOPO_CHANNEL_SEASONALITY_NEW;

--REGION MATSER의 REGIONID값 74
SELECT DISTINCT REGIONID
FROM KOPO_REGION_MST;

--중복되지 않는값 == 5개
SELECT DISTINCT REGIONID
FROM KOPO_REGION_MST
WHERE 1=1
AND REGIONID NOT IN(SELECT DISTINCT REGIONID
                    FROM KOPO_CHANNEL_SEASONALITY_NEW)